### ISSUE TITLE
[README] Client : Invalid starting command

### ISSUE THREAD

**Issue by Antoine-Bergerault** [ligue-dev/ligue-game-client#1]
Le script `start` n'existe pas. Le projet ne se lance donc pas avec un `npm run start`.
Fonctionne avec `npm run dev`

**Comment by ArthurDelamare** [comment]
C'est corrigé, merci de ta remarque. La bonne commande est bien ```npm run dev```. J'ai confondu les commandes du client et du serveur en l'écrivant.
